// import './globals.css'
import type { Metadata } from 'next';
import { PropsWithChildren } from 'react';

export const metadata: Metadata = {
    title: 'Counter',
    description: 'Generated by create next app',
}

export default function CounterLayout({
    children,
}: PropsWithChildren) {
    return (
        <>{children}</>
    )
}
